import { NavLink } from "react-router-dom";
import { SiteFrame } from "../components/SiteFrame";
import { UnderstandingSystem } from "../components/PublicVisuals";

export function AboutPage() {
  return <SiteFrame pageTitle="About">
    <header className="page-hero"><p className="eyebrow">Intrinsic Systems</p><h1>Helping organisations own the understanding behind improvement.</h1><p className="lede">We are an Australian company developing CORE: a guided, software-supported way for asset-intensive organisations to connect knowledge and evidence, determine what needs to improve and retain what they learn.</p></header>
    <section className="content-section section-grid section-grid--middle"><UnderstandingSystem compact /><div><p className="eyebrow">Why we exist</p><h2>Good insight should remain useful.</h2><p className="body-large">Organisations invest in systems, standards, advice and experienced people. The reasoning that connects them can be lost when a report is filed, a project ends or a person leaves. CORE is designed to make that understanding visible, maintainable and owned by the organisation.</p></div></section>
    <section className="content-section content-section--tinted"><div className="section-heading section-heading--wide"><p className="eyebrow">How we approach the work</p><h2>Three principles guide us.</h2></div><div className="principle-grid"><article><b>01</b><h3>Start with your purpose</h3><p>Your operational needs, financial priorities and desired outcomes define what good should mean.</p></article><article><b>02</b><h3>Keep reasoning visible</h3><p>People should be able to examine the evidence, judgement and uncertainty behind each material finding.</p></article><article><b>03</b><h3>Keep decisions accountable</h3><p>Technology can guide and retain the process. Decisions remain with the people responsible for their consequences.</p></article></div></section>
    <section className="content-section split-copy"><div><p className="eyebrow">Where we begin</p><h2>Asset-intensive environments where incomplete understanding has real consequences.</h2></div><div><p>Governance, asset information, lifecycle planning, risk, investment and operational performance are closely connected. CORE helps organisations understand those connections before committing to an improvement solution.</p><NavLink className="text-link" to="/contact">Discuss a CORE pilot <span>→</span></NavLink></div></section>
  </SiteFrame>;
}
