import { NavLink } from "react-router-dom";
import { SiteFrame } from "../components/SiteFrame";
import { RetainedUnderstandingPath, UnderstandingJourney, UnderstandingSystem } from "../components/PublicVisuals";

export function HomePage() {
  return <SiteFrame pageTitle="Organisational intelligence">
    <section className="hero section-grid">
      <div>
        <p className="eyebrow">CORE by Intrinsic Systems</p>
        <h1>Embed the understanding required to improve.</h1>
        <p className="lede">CORE helps asset-intensive organisations connect their knowledge, evidence, objectives and constraints. This creates a clearer basis for understanding capability, deciding what should improve and governing the work that follows.</p>
        <div className="actions"><NavLink className="button" to="/framework">Explore CORE <span>→</span></NavLink><NavLink className="text-link" to="/contact">Discuss a pilot <span>↗</span></NavLink></div>
      </div>
      <UnderstandingSystem />
    </section>
    <section className="statement-band"><p>Asset-management improvement begins with organisational understanding.</p><h2>Know what needs to improve—and why.</h2><span>Operational knowledge, evidence, financial priorities and previous advice often sit in different places. CORE brings them into a maintained view that your organisation can use, test and build upon.</span></section>
    <section className="content-section"><div className="section-heading"><p className="eyebrow">What gets lost</p><h2>The records remain.<br />The reasoning can fade.</h2><p>Context changes. Projects end. People move on. Unless the links between evidence, judgement and action are kept, valuable understanding gradually disappears.</p></div><div className="principle-grid"><article><b>01</b><h3>Bring the picture together</h3><p>Connect people’s knowledge with evidence and information from the systems they already use.</p></article><article><b>02</b><h3>Understand what matters</h3><p>Show strengths, constraints and uncertainty so the organisation can define what good means in its circumstances.</p></article><article><b>03</b><h3>Retain what is learned</h3><p>Keep the reasoning behind findings, decisions and actions available for the next review.</p></article></div></section>
    <section className="approach-section"><div className="approach-section__intro"><p className="eyebrow">From repeated diagnosis to retained understanding</p><h2>Your next review should begin with what your organisation already knows.</h2><p>CORE keeps the links between evidence, interpretation, decisions and results. New work can extend the organisational picture instead of reconstructing it.</p></div><RetainedUnderstandingPath /></section>
    <section className="content-section"><div className="section-heading section-heading--wide"><p className="eyebrow">What you are buying</p><h2>The means to understand, plan and govern your own improvement.</h2><p>CORE is being developed as a guided, software-supported service for leaders responsible for asset management, operations, risk, investment and improvement. The intended result is a maintained capability baseline, supported findings, decision history and prioritised improvement plan owned by the organisation.</p></div><div className="principle-grid"><article><b>01</b><h3>A supported capability position</h3><p>Findings remain connected to the organisational knowledge, evidence and context that support them.</p></article><article><b>02</b><h3>An organisation-owned improvement path</h3><p>Priorities reflect your operational needs, financial constraints, risks and intended benefits.</p></article><article><b>03</b><h3>A clearer basis for delivery</h3><p>Use the plan internally or engage specialists against a better-defined scope and measurable outcomes.</p></article></div></section>
    <section className="content-section content-section--dark"><div className="section-heading section-heading--wide"><p className="eyebrow">The customer experience</p><h2>From the first question to measured improvement.</h2><p>Your people provide the context, evidence, objectives and constraints. CORE helps organise and test that knowledge, guide the decisions that follow and retain what is learned.</p></div><UnderstandingJourney /></section>
    <section className="content-section split-copy"><div><p className="eyebrow">Use expertise where it adds value</p><h2>Keep the understanding inside your organisation.</h2></div><div><p>CORE helps clarify where specialist advice or delivery support is required, why it is required and what success should achieve. Consultants can contribute expertise and execution while your organisation retains the evidence, reasoning and decision history.</p><NavLink className="text-link" to="/framework">See how CORE works <span>→</span></NavLink></div></section>
    <section className="cta-band"><div><p className="eyebrow">For asset-intensive organisations</p><h2>Begin with the capability question that matters.</h2></div><NavLink className="button button--light" to="/contact">Discuss a pilot <span>→</span></NavLink></section>
  </SiteFrame>;
}
