import { NavLink } from "react-router-dom";
import { SiteFrame } from "../components/SiteFrame";
import { CoreInformationIntake, RetainedUnderstandingPath, UnderstandingJourney, UnderstandingSystem } from "../components/PublicVisuals";

export function HomePage() {
  return <SiteFrame pageTitle="Organisational intelligence">
    <section className="hero section-grid">
      <div>
        <p className="eyebrow">CORE by Intrinsic Systems</p>
        <h1>Understand how your asset-management organisation is working—and what needs to improve.</h1>
        <p className="lede">CORE is being developed as a SaaS platform for asset-intensive organisations. It brings assessments, operational knowledge, evidence and organisational priorities into one maintained capability position, then helps accountable people determine and govern what happens next.</p>
        <div className="actions"><NavLink className="button" to="/framework">Explore CORE <span>→</span></NavLink><NavLink className="text-link" to="/contact">Discuss a pilot <span>↗</span></NavLink></div>
      </div>
      <CoreInformationIntake />
    </section>
    <section className="product-summary" aria-label="CORE product summary"><div><span>What</span><strong>Asset-management capability and improvement software.</strong></div><div><span>Who</span><strong>Organisations responsible for infrastructure, operations and long-life assets.</strong></div><div><span>How</span><strong>Guided assessment, organisational evidence and adaptive analysis.</strong></div><div><span>Outcome</span><strong>Supported findings, visible priorities and a governed improvement plan.</strong></div></section>
    <section className="statement-band"><p>Asset managers already have systems, reports, standards and expert advice.</p><h2>What they often lack is one maintained understanding of how those elements work together.</h2><span>When that understanding is fragmented, improvement is harder to prioritise, difficult to govern and vulnerable to being lost when projects end or people leave.</span></section>
    <section className="content-section section-grid section-grid--middle connected-understanding"><UnderstandingSystem /><div><p className="eyebrow">Connected organisational understanding</p><h2>Embed the understanding required to improve.</h2><p className="body-large">CORE connects what your people know with the evidence available, the outcomes the organisation needs and the decisions it must make. The result is a capability position that can be examined, maintained and used as improvement proceeds.</p></div></section>
    <section className="content-section"><div className="section-heading"><p className="eyebrow">What gets lost</p><h2>The records remain.<br />The reasoning can fade.</h2><p>Context changes. Projects end. People move on. Unless the links between evidence, judgement and action are kept, valuable understanding gradually disappears.</p></div><div className="principle-grid"><article><b>01</b><h3>Bring the picture together</h3><p>Connect people’s knowledge with evidence and information from the systems they already use.</p></article><article><b>02</b><h3>Understand what matters</h3><p>Show strengths, constraints and uncertainty so the organisation can define what good means in its circumstances.</p></article><article><b>03</b><h3>Retain what is learned</h3><p>Keep the reasoning behind findings, decisions and actions available for the next review.</p></article></div></section>
    <section className="approach-section"><div className="approach-section__intro"><p className="eyebrow">From repeated diagnosis to retained understanding</p><h2>Your next review should begin with what your organisation already knows.</h2><p>Traditional maturity assessments can provide a useful snapshot, but their evidence, interpretation and delivery learning are often separated as reports and projects progress. CORE is intended to bring that material into one maintained model and make it usable through an executive capability view—so leaders can see the current position, what supports it and what requires action.</p></div><RetainedUnderstandingPath /></section>
    <section className="content-section"><div className="section-heading section-heading--wide"><p className="eyebrow">What you are buying</p><h2>The means to understand, plan and govern your own improvement.</h2><p>CORE is being developed as a guided, software-supported service for leaders responsible for asset management, operations, risk, investment and improvement. The intended result is a maintained capability baseline, supported findings, decision history and prioritised improvement plan owned by the organisation.</p></div><div className="principle-grid"><article><b>01</b><h3>A supported capability position</h3><p>Findings remain connected to the organisational knowledge, evidence and context that support them.</p></article><article><b>02</b><h3>An organisation-owned improvement path</h3><p>Priorities reflect your operational needs, financial constraints, risks and intended benefits.</p></article><article><b>03</b><h3>A clearer basis for delivery</h3><p>Use the plan internally or engage specialists against a better-defined scope and measurable outcomes.</p></article></div></section>
    <section className="content-section content-section--tinted split-copy future-ai"><div><p className="eyebrow">Proposed capability</p><h2>Build the understanding AI needs before asking it to guide decisions.</h2></div><div><p>Asset-intensive organisations are exploring AI to improve forecasting, strategic asset planning, lifecycle decisions and investment choices. Its value, however, depends on the quality and context of the information it can use.</p><p>CORE is intended to provide that governed foundation: structured organisational knowledge, traceable evidence, explicit objectives and constraints, and a retained history of the decisions that follow.</p><p className="note">Future AI-enabled services are intended to help reveal relationships, test scenarios and develop better-supported planning options. Accountable people would remain responsible for the decisions and able to examine why an option was proposed.</p></div></section>
    <section className="content-section content-section--dark"><div className="section-heading section-heading--wide"><p className="eyebrow">The customer experience</p><h2>From the first question to measured improvement.</h2><p>Your people provide the context, evidence, objectives and constraints. CORE helps organise and test that knowledge, guide the decisions that follow and retain what is learned.</p></div><UnderstandingJourney /></section>
    <section className="content-section split-copy"><div><p className="eyebrow">Use expertise where it adds value</p><h2>Keep the understanding inside your organisation.</h2></div><div><p>CORE helps clarify where specialist advice or delivery support is required, why it is required and what success should achieve. Consultants can contribute expertise and execution while your organisation retains the evidence, reasoning and decision history.</p><NavLink className="text-link" to="/framework">See how CORE works <span>→</span></NavLink></div></section>
    <section className="cta-band"><div><p className="eyebrow">For asset-intensive organisations</p><h2>Begin with the capability question that matters.</h2></div><NavLink className="button button--light" to="/contact">Discuss a pilot <span>→</span></NavLink></section>
  </SiteFrame>;
}
