import { NavLink } from "react-router-dom";
import { SiteFrame } from "../components/SiteFrame";
import { UnderstandingSystem,EvidenceLoop } from "../components/PublicVisuals";
export function HomePage(){return <SiteFrame pageTitle="Organisational intelligence">
  <section className="hero section-grid"><div><p className="eyebrow">Organisational intelligence</p><h1>See your organisation clearly. Strengthen what matters.</h1><p className="lede">Every organisation is different. We bring its knowledge, evidence and experience together so people can see where things stand, decide what good looks like, and focus improvement where it matters most.</p><div className="actions"><NavLink className="button" to="/framework">Explore the framework <span>→</span></NavLink><NavLink className="text-link" to="/about">Why Intrinsic Systems <span>↗</span></NavLink></div></div><UnderstandingSystem/></section>
  <section className="statement-band"><p>Most organisations have more information than ever.</p><h2>The challenge is making sense of it together.</h2><span>Important decisions draw on systems, reports, standards and experience. The connections between them are often left for people to reconstruct each time.</span></section>
  <section className="content-section"><div className="section-heading"><p className="eyebrow">What gets lost</p><h2>The records remain.<br/>The reasoning can fade.</h2><p>Context changes. Projects end. People move on. Unless the links between evidence, judgement and action are kept, valuable understanding gradually disappears.</p></div><div className="principle-grid"><article><b>01</b><h3>Bring the picture together</h3><p>Connect people’s knowledge with evidence and information from the systems they already use.</p></article><article><b>02</b><h3>See where things stand</h3><p>Show strengths, gaps and uncertainty clearly so the organisation can define what good means in its own setting.</p></article><article><b>03</b><h3>Choose the next step</h3><p>Help people focus on the question, contribution or action that will make the greatest difference.</p></article></div></section>
  <section className="content-section content-section--tinted section-grid section-grid--middle"><div><p className="eyebrow">Understanding that grows</p><h2>A clearer picture with every contribution.</h2><p className="body-large">The framework keeps evidence, decisions and outcomes connected. As people contribute and conditions change, the organisation’s understanding becomes richer and more useful.</p><NavLink className="text-link" to="/framework">See how the framework works <span>→</span></NavLink></div><EvidenceLoop/></section>
  <section className="cta-band"><div><p className="eyebrow">For complex organisations</p><h2>Begin with a question that matters.</h2></div><NavLink className="button button--light" to="/contact">Start a conversation <span>→</span></NavLink></section>
</SiteFrame>}
