import { NavLink } from "react-router-dom";
import { SiteFrame } from "../components/SiteFrame";
import { ArchitectureStack, EvidenceLoop } from "../components/PublicVisuals";
import { CapabilityRadial } from "../components/CapabilityRadial";

export function OasisSuitePage() {
  return <SiteFrame pageTitle="CORE">
    <header className="page-hero"><p className="eyebrow">CORE by Intrinsic Systems</p><h1>Build the understanding to choose what comes next.</h1><p className="lede">CORE is a guided, software-supported asset-management capability service. It helps your organisation establish where it stands, understand what is limiting performance and govern an evidence-backed improvement path.</p></header>
    <section className="content-section"><div className="section-heading section-heading--wide"><p className="eyebrow">What an engagement involves</p><h2>Your knowledge becomes a maintained organisational capability.</h2><p>Your organisation supplies relevant participants, evidence, operational context, strategic objectives and constraints. CORE structures and tests that knowledge so accountable people can make and retain better-supported decisions.</p></div><div className="principle-grid principle-grid--four"><article><b>01</b><h3>Establish</h3><p>Scope the need and create an evidence-backed capability baseline.</p></article><article><b>02</b><h3>Understand</h3><p>Investigate material constraints, dependencies and uncertainty.</p></article><article><b>03</b><h3>Plan</h3><p>Prioritise improvement against risk, value, capacity and intended benefits.</p></article><article><b>04</b><h3>Govern</h3><p>Retain the reasoning, responsibilities and measures as work proceeds.</p></article></div></section>
    <section className="content-section content-section--tight"><ArchitectureStack /></section>
    <section className="radial-section"><div className="radial-section__intro"><p className="eyebrow">How CORE develops the picture</p><h2>Start with the question that matters.</h2><p>CORE examines organisational capability through four connected fields. Each provides a different lens on the same capability position.</p></div><CapabilityRadial /></section>
    <section className="content-section section-grid"><div className="section-heading"><p className="eyebrow">The starting experience</p><h2>Establish a supported baseline.</h2><p>CORE begins with an important question about asset-management capability. It brings together operational context, what people understand to be true and the evidence available to support it.</p><p className="note">Runtime guidance is being developed to select the next useful enquiry, show what remains uncertain and preserve why a finding or action follows.</p></div><EvidenceLoop /></section>
    <section className="content-section content-section--tinted"><div className="section-heading section-heading--wide"><p className="eyebrow">Services shaped by organisational need</p><h2>Maintain, improve and extend the picture.</h2><p>CORE’s service model can continue beyond the initial baseline. The scope depends on the organisation’s needs rather than requiring a collection of separate applications.</p></div><div className="principle-grid principle-grid--four"><article><b>MONITOR</b><h3>Keep the position current</h3><p>Review material changes in capability, evidence, risk and performance.</p></article><article><b>IMPROVE</b><h3>Turn understanding into action</h3><p>Develop priorities, responsibilities, dependencies and measurable benefits.</p></article><article><b>ANTICIPATE</b><h3>Consider what lies ahead</h3><p>Test future conditions and choices against the maintained organisational context.</p></article><article><b>EXTEND</b><h3>Add relevant context</h3><p>Apply relationship or spatial views where they strengthen a specific decision.</p></article></div></section>
    <section className="content-section"><div className="section-heading section-heading--wide"><p className="eyebrow">Understanding you can examine</p><h2>See what supports each conclusion.</h2></div><div className="principle-grid principle-grid--four"><article><b>01</b><h3>Capability claim</h3><p>State clearly what is understood about the organisation’s current position.</p></article><article><b>02</b><h3>Evidence in context</h3><p>Keep the source, relevance, date and limitations of evidence visible.</p></article><article><b>03</b><h3>Confidence and control</h3><p>Show what is supported, what is contested and what requires attention.</p></article><article><b>04</b><h3>Accountable decision</h3><p>Technology organises and traces the reasoning. Responsible people decide.</p></article></div></section>
    <section className="content-section split-copy"><div><p className="eyebrow">Built around your organisation</p><h2>Your purpose sets the direction.</h2></div><div><p>Standards, benchmarks and industry practices provide valuable reference points. Your operational needs, financial priorities, risks and desired outcomes determine the appropriate path.</p><p className="note">Engage specialists where their expertise adds value. Keep the resulting understanding and decision history inside your organisation.</p><NavLink className="text-link" to="/contact">Discuss a CORE pilot <span>→</span></NavLink></div></section>
  </SiteFrame>;
}
