import type { DomainNode } from "./orgGovTypes";

export const orgGovMock: DomainNode = {
  id: "ORG_GOV",
  title: "Organisation & Governance",
  description:
    "Defines how asset management is directed, governed, assured, and enabled across the enterprise.",
  score: {
    current: 3.3,
    benchmark: 4.0,
    target: 4.5,
    variance: -0.7,
    confidence: 0.83,
  },
  elements: [
    {
      id: "OG_E1",
      title: "Strategic Direction & Policy",
      weight: 0.18,
      score: { current: 3.4, benchmark: 4.1, target: 4.5, variance: -0.7, confidence: 0.85 },
      questions: [
        {
          id: "OG_E1_Q1",
          prompt:
            "To what extent is asset management explicitly embedded in the organisation’s vision and strategic direction, with sufficient clarity to drive asset management objectives and plans?",
          type: "STRUCTURAL",
          weight: 0.2,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 3.0, benchmark: 4.0, target: 4.5, variance: -1.0, confidence: 0.86 },
          evidenceItems: [
            {
              id: "EV-001",
              type: "DOCUMENT",
              title: "Corporate Strategy 2026–2030",
              reference: "STRAT-2026-01",
              verified: true,
              owner: "Executive Office",
              date: "2026-02-12",
            },
          ],
        },
        {
          id: "OG_E1_Q2",
          prompt: "How well aligned is the asset management policy with the organisation’s strategic direction and asset management intent?",
          type: "GOVERNANCE",
          weight: 0.18,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 3.5, benchmark: 4.1, target: 4.6, variance: -0.6, confidence: 0.88 },
          evidenceItems: [
            {
              id: "EV-002",
              type: "POLICY",
              title: "Asset Management Policy v2.1",
              verified: true,
              owner: "Asset Strategy",
              date: "2026-01-15",
            },
          ],
        },
        {
          id: "OG_E1_Q3",
          prompt: "How effectively are the asset management policy, strategy, and plans communicated to relevant internal and external stakeholders?",
          type: "INTEGRATION",
          weight: 0.15,
          isCritical: false,
          evidenceRequired: true,
          score: { current: 3.6, benchmark: 4.0, target: 4.4, variance: -0.4, confidence: 0.81 },
          evidenceItems: [
            {
              id: "EV-003",
              type: "REPORT",
              title: "AM Communication Pack",
              verified: false,
              owner: "Corporate Affairs",
              date: "2025-11-10",
            },
          ],
        },
      ],
    },
    {
      id: "OG_E2",
      title: "Governance, Accountability & Oversight",
      weight: 0.18,
      score: { current: 3.2, benchmark: 4.0, target: 4.4, variance: -0.8, confidence: 0.82 },
      questions: [
        {
          id: "OG_E2_Q1",
          prompt: "How clearly defined is ownership and accountability for asset management?",
          type: "GOVERNANCE",
          weight: 0.2,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 3.3, benchmark: 4.1, target: 4.4, variance: -0.8, confidence: 0.84 },
          evidenceItems: [
            {
              id: "EV-004",
              type: "DOCUMENT",
              title: "AM Governance Charter",
              verified: true,
              owner: "Asset Governance",
              date: "2026-02-04",
            },
          ],
        },
        {
          id: "OG_E2_Q2",
          prompt: "How regularly is asset management performance reviewed by leadership?",
          type: "PERFORMANCE",
          weight: 0.18,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 3.1, benchmark: 3.9, target: 4.3, variance: -0.8, confidence: 0.79 },
          evidenceItems: [
            {
              id: "EV-005",
              type: "MINUTES",
              title: "Executive Performance Review Minutes",
              verified: true,
              owner: "Office of the COO",
              date: "2026-02-28",
            },
          ],
        },
      ],
    },
    {
      id: "OG_E3",
      title: "Compliance, Standards & Assurance",
      weight: 0.16,
      score: { current: 3.1, benchmark: 4.0, target: 4.4, variance: -0.9, confidence: 0.8 },
      questions: [
        {
          id: "OG_E3_Q1",
          prompt: "To what extent are standards and legislation embedded into asset management planning?",
          type: "COMPLIANCE",
          weight: 0.3,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 3.2, benchmark: 4.1, target: 4.5, variance: -0.9, confidence: 0.82 },
          evidenceItems: [
            {
              id: "EV-006",
              type: "REGISTER",
              title: "Standards and Compliance Register",
              verified: true,
              owner: "Compliance",
              date: "2026-03-05",
            },
          ],
        },
        {
          id: "OG_E3_Q2",
          prompt: "How effectively are compliance and assurance processes implemented and reviewed?",
          type: "ASSURANCE",
          weight: 0.25,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 3.0, benchmark: 3.9, target: 4.3, variance: -0.9, confidence: 0.78 },
          evidenceItems: [
            {
              id: "EV-007",
              type: "REPORT",
              title: "Internal Assurance Review 2026",
              verified: true,
              owner: "Internal Audit",
              date: "2026-03-08",
            },
          ],
        },
      ],
    },
    {
      id: "OG_E4",
      title: "Information & Data Governance",
      weight: 0.18,
      score: { current: 3.5, benchmark: 4.0, target: 4.6, variance: -0.5, confidence: 0.84 },
      questions: [
        {
          id: "OG_E4_Q1",
          prompt: "How well defined is the organisation’s asset information and data strategy?",
          type: "DATA",
          weight: 0.25,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 3.5, benchmark: 4.0, target: 4.6, variance: -0.5, confidence: 0.85 },
          evidenceItems: [
            {
              id: "EV-008",
              type: "DOCUMENT",
              title: "Asset Information Strategy",
              verified: true,
              owner: "Digital Asset Office",
              date: "2026-01-29",
            },
          ],
        },
        {
          id: "OG_E4_Q2",
          prompt: "To what extent are data standards applied across asset information?",
          type: "DATA",
          weight: 0.25,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 3.4, benchmark: 4.1, target: 4.6, variance: -0.7, confidence: 0.83 },
          evidenceItems: [
            {
              id: "EV-009",
              type: "WORKFLOW",
              title: "Asset Data Standard Operating Rules",
              verified: true,
              owner: "Data Governance",
              date: "2026-02-14",
            },
          ],
        },
      ],
    },
    {
      id: "OG_E5",
      title: "Operating Framework & Procedures",
      weight: 0.15,
      score: { current: 3.6, benchmark: 4.0, target: 4.4, variance: -0.4, confidence: 0.86 },
      questions: [
        {
          id: "OG_E5_Q1",
          prompt: "To what extent are standardised asset management procedures defined and used?",
          type: "PROCESS",
          weight: 0.3,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 3.7, benchmark: 4.1, target: 4.5, variance: -0.4, confidence: 0.87 },
          evidenceItems: [
            {
              id: "EV-010",
              type: "WORKFLOW",
              title: "Asset SOP Library",
              verified: true,
              owner: "Operations Excellence",
              date: "2026-02-01",
            },
          ],
        },
        {
          id: "OG_E5_Q2",
          prompt: "How accessible and usable are procedures across the organisation?",
          type: "SYSTEM",
          weight: 0.25,
          isCritical: false,
          evidenceRequired: true,
          score: { current: 3.4, benchmark: 3.9, target: 4.3, variance: -0.5, confidence: 0.84 },
          evidenceItems: [
            {
              id: "EV-011",
              type: "SYSTEM_RECORD",
              title: "Document Portal Usage Report",
              verified: false,
              owner: "Knowledge Services",
              date: "2026-02-20",
            },
          ],
        },
      ],
    },
    {
      id: "OG_E6",
      title: "Resourcing & Decision Support",
      weight: 0.15,
      score: { current: 3.0, benchmark: 3.9, target: 4.4, variance: -0.9, confidence: 0.77 },
      questions: [
        {
          id: "OG_E6_Q1",
          prompt: "To what extent are costed scenarios used to support asset management decisions?",
          type: "DECISION_SUPPORT",
          weight: 0.3,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 2.9, benchmark: 3.9, target: 4.4, variance: -1.0, confidence: 0.75 },
          evidenceItems: [
            {
              id: "EV-012",
              type: "FINANCIAL_MODEL",
              title: "Scenario Options Model FY26",
              verified: true,
              owner: "Finance Planning",
              date: "2026-03-02",
            },
          ],
        },
        {
          id: "OG_E6_Q2",
          prompt: "How comprehensive is financial planning for asset management?",
          type: "FINANCIAL",
          weight: 0.25,
          isCritical: true,
          evidenceRequired: true,
          score: { current: 3.1, benchmark: 4.0, target: 4.4, variance: -0.9, confidence: 0.79 },
          evidenceItems: [
            {
              id: "EV-013",
              type: "PLAN",
              title: "AM Financial Planning Pack",
              verified: true,
              owner: "Finance",
              date: "2026-02-17",
            },
          ],
        },
      ],
    },
  ],
};
